# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

- task: CmdLine@2
inputs:
script: |
buildah bud --tls-verify=0 --format=docker -t
alerantdevopsbootcamp.azurecr.io/bootcamp/demoapp_student5 -f
Dockerfile .
buildah login --tls-verify=0 -u alerantdevopsbootcamp -p
VQq7EvmIbRzlT9N6Z/HA4xND8=dQYyYg alerantdevopsbootcamp.azurecr.io
buildah push alerantdevopsbootcamp.azurecr.io/bootcamp/student5